version: '3'
services:
  ####################
  # Setup server
  ####################
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    # depends_on:
    #   - mongo
    expose:
      - 5000
    environment:
      NODE_ENV: production
      COOKIE_KEY: sdkhjasduhsdkjhksdfhj8wj
      GOOGLE_CLIENT_ID: 881384575505-297qhcjfinr9fqdsf7vcbps3lsa6cltl.apps.googleusercontent.com
      MONGO_URI: mongodb+srv://royhersh:ye5OqTgzxDmuiZl2@cluster0-4ql12.mongodb.net/dayssince?retryWrites=true&w=majority
      SECRET: top-sectet

    restart: on-failure
    command: npm run start
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
