version: '3'

services:
  ####################
  # Setup server
  ####################
  server:
    build: ./server
    depends_on:
      - mongo
    environment:
      - PLATFORM=docker-compose
    expose:
      - 5000
    restart: on-failure
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  ####################
  # Setup client
  ####################
  client:
    build: ./client
    command: npm run start
    environment:
      - PLATFORM=docker-compose
    expose:
      - 3000
    ports:
      - '3000:3000'
    # working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  ####################
  # Setup MongoDB
  ####################
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-db:/data/db
    ports:
      - '27017:27017'

volumes:
  data-db:
