version: '3'

services:
  ####################
  # Setup server
  ####################
  server:
    build: ./server
    depends_on:
      - mongo
    expose:
      - 5000
    restart: on-failure
    command: npm run start
  ####################
  # Setup client
  ####################
  client:
    build: ./client
    command: npm run start
    environment:
      - PLATFORM=docker-compose
    expose:
      - 3000
    ports:
      - '3000:3000'

  ####################
  # Setup MongoDB
  ####################
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-db:/data/db
    ports:
      - '27017:27017'
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - app-static:/srv/www/static
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - client
volumes:
  data-db:
